// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyqnzodileepoydfcaad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cW56b2RpbGVlcG95ZGZjYWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDk4NjEsImV4cCI6MjA2NzcyNTg2MX0.SIZxpVi_aFrdT9y8SA8fJdtg9FVxzwThkbI5r4sYhkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});